variables:
  Environment: 'Test' 
  AdoEnvironment: 'test-data'

  # Data lz variables
  SubscriptionIdData: "3be2ce56-4a5f-4034-88d7-2953d1819ed3"
  ResourceGroupNameData: "terrraf-${{ lower(variables.Environment) }}-uks-01"
