name: Pipeline-$(Build.DefinitionName)-$(Date:yyyyMMdd)$(Rev:.r)

pr: none
trigger: none

variables:
- template: ..\Variables\Variables-Global.yml

pool: 'Azure Pipelines'


stages:

- template: ..\Stages\01-Stage-Environment.yml
  parameters:
          ServiceConnection: ${{ variables.serviceConnection }}
          Environment: ${{ variables.TestEnvironment }}
          Location: ${{ variables.Location }}




